### ISSUE TITLE
handle ? and U characters in GISAID format files

### ISSUE THREAD

**Issue by gregcaporaso** [caporaso-lab/genome-sampler#41]
I came across both in GISAID downloaded sequence data today, and they caused imports to fail. I think this should be handled by first replacing any U or u characters in sequences with a T, and then dropping any sequences that still contain characters that are outside of the IUPAC DNA alphabet (the `?` probably implies `N`, but I'm not comfortable with generally, silently making that assumption).

**Comment by ebolyen** [comment]
fixed in #42
