### ISSUE TITLE
running the tutorial yields a KeyError.

### ISSUE THREAD

**Issue by ctb** [caporaso-lab/genome-sampler#70]
```
[Wed Aug 26 08:16:24 2020]
rule import_context_seqs:
    input: context-seqs.fasta
    output: context-seqs.qza
    jobid: 4

Traceback (most recent call last):
  File "/home/ctbrown/miniconda3/envs/genome-sampler/lib/python3.6/site-packages/qiime2/sdk/util.py", line 90, in parse_format
    format_record = pm.formats[format_str]
KeyError: 'GISAIDDNAFASTAFormat'
```
any thoughts?

**Comment by thermokarst** [comment]
Hi @ctb - what version of genome-sampler do you have installed? Can you run the following (inside the conda env with genome-sampler installed in it) and report the results here:

```bash
qiime info
conda list
```

Thanks!

**Comment by ctb** [comment]
I installed latest master via the tutorial instructions, just now.
(pip doesn't seem to list it in pip show, which seems a bit odd.)

qiime info:

```
System versions
Python version: 3.6.11
QIIME 2 release: 2020.2
QIIME 2 version: 2020.2.0
q2cli version: 2020.2.0

Installed plugins
feature-table: 2020.2.0
metadata: 2020.2.0
types: 2020.2.0

Application config directory
/home/ctbrown/miniconda3/envs/genome-sampler/var/q2cli

Getting help
To get help with QIIME 2, visit https://qiime2.org
```

conda list file attached.
[conda.list.txt](https://github.com/caporaso-lab/genome-sampler/files/5131239/conda.list.txt)

**Comment by ctb** [comment]
hah! turns out I forgot that step 🙈

```
% pip list | grep -i geno
genome-sampler                2020.6.1+9.g3b17a70
```
...and snakemake is now running fine. I'll close this issue then :).

I'd maybe suggest adding an `import genome_sampler` at the top of the snakefile to produce a clearer error :)
